classDiagram
    class Client
    Client : +String firstName
    Client : +String lastName
    Client : +String email
    Client : +String password
    Client : +int phoneNumber 

    class Admin
    Admin : +view_all_clients()
    Admin : +modify_client()
    Admin : +delete_client()
    Admin : +search_client()
    Admin : +add_client()